version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Djum@0105
      MYSQL_DATABASE: projectdb
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project_network
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       interval: 10s
       timeout: 5s
       retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Djum@0105
      DB_NAME: projectdb
      DB_PORT: 3306
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - project_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - project_network

volumes:
  db_data:

networks:
  project_network:
    driver: bridge
